# Generated by Django 2.0.1 on 2018-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('checked_up', models.BooleanField()),
                ('checked_up_by_whom', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('keywords', models.CharField(max_length=250)),
                ('authors', models.CharField(max_length=250)),
                ('cover', models.CharField(max_length=1000)),
                ('checking_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AVFile',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Documents.Document')),
            ],
            bases=('Documents.document',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Documents.Document')),
                ('publisher', models.CharField(max_length=250)),
                ('edition', models.IntegerField()),
                ('publication_date', models.CharField(max_length=250)),
            ],
            bases=('Documents.document',),
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Documents.Document')),
            ],
            bases=('Documents.document',),
        ),
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Documents.Document')),
                ('publisher_journal', models.CharField(max_length=250)),
                ('editors', models.CharField(max_length=250)),
                ('publication_date', models.CharField(max_length=250)),
            ],
            bases=('Documents.document',),
        ),
    ]
