# Generated by Django 2.0.1 on 2018-01-31 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='checked_up_by_whom',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-01-31 08:22'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='doc',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Documents.Document'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-01-31 08:22'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='editors',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='publication_date',
            field=models.DateField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='publisher_journal',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
