# Generated by Django 2.0.1 on 2018-02-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcopy',
            name='level',
        ),
        migrations.RemoveField(
            model_name='documentcopy',
            name='room',
        ),
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='room',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-02-11 16:46'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-02-11 16:46'),
        ),
    ]
