# Generated by Django 2.0.2 on 2018-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_auto_20180211_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcopy',
            name='renewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-02-20 13:39'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-02-20 13:39'),
        ),
    ]
