# Generated by Django 2.0.1 on 2018-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_auto_20180220_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcopy',
            name='renewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-02-20 14:39'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-02-20 14:39'),
        ),
    ]
