# Generated by Django 2.0.1 on 2018-01-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_auto_20180131_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcopy',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-01-31 18:32'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-01-31 18:32'),
        ),
    ]
