# Generated by Django 2.0.1 on 2018-01-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_document_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='h',
            field=models.CharField(default='h', max_length=200),
        ),
    ]
