# Generated by Django 2.0.1 on 2018-02-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_auto_20180131_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcopy',
            name='price',
        ),
        migrations.AddField(
            model_name='documentcopy',
            name='fine_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-02-02 11:38'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-02-02 11:38'),
        ),
    ]
