# Generated by Django 2.0.1 on 2018-01-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_document_h'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
