# Generated by Django 2.0.1 on 2018-02-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_auto_20180220_1339'),
        ('Documents', '0005_auto_20180220_1453'),
    ]

    operations = [
    ]
