# Generated by Django 2.0.1 on 2018-02-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0005_userProfileModel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcopy',
            options={'verbose_name_plural': 'Document copies'},
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-02-03 14:38'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-02-03 14:38'),
        ),
    ]
