# Generated by Django 2.0.1 on 2018-01-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserCards', '0001_initial'),
        ('Documents', '0005_documentcopy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='checked_up_by_whom',
        ),
        migrations.RemoveField(
            model_name='document',
            name='h',
        ),
        migrations.AddField(
            model_name='documentcopy',
            name='checked_up_by_whom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserCards.UserCard'),
        ),
        migrations.AddField(
            model_name='documentcopy',
            name='doc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Documents.Document'),
        ),
    ]
