# Generated by Django 2.0.1 on 2018-01-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0006_auto_20180119_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='copies',
            new_name='_copies',
        ),
    ]
