# Generated by Django 2.0.1 on 2018-01-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0007_auto_20180119_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='_copies',
            new_name='copies',
        ),
        migrations.RemoveField(
            model_name='document',
            name='checked_up',
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='checked_up_by_whom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserCards.UserCard'),
        ),
    ]
