# Generated by Django 2.0.1 on 2018-02-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0007_auto_20180205_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-02-05 22:47'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-02-05 22:47'),
        ),
    ]
