# Generated by Django 2.0.1 on 2018-01-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0008_auto_20180119_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cover',
            field=models.CharField(default='https://lh3.googleusercontent.com/zqfUbCXdb1oGmsNEzNxTjQU5ZlS3x46nQoB83sFbRSlMnpDTZgdVCe_LvCx-rl7sOA=w300', max_length=1000),
        ),
    ]
