# Generated by Django 2.0.1 on 2018-01-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0009_auto_20180120_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='checking_time',
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(max_length=250),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='publication_date',
            field=models.DateField(max_length=250),
        ),
    ]
