# Generated by Django 2.0.1 on 2018-04-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0011_auto_20180403_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-04-03 17:10'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-04-03 17:10'),
        ),
    ]
