# Generated by Django 2.0.1 on 2018-01-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0011_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcopy',
            name='date',
            field=models.DateField(default='2018-01-20'),
        ),
        migrations.AddField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateField(default='2018-01-20'),
        ),
    ]
