# Generated by Django 2.0.1 on 2018-01-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0013_auto_20180123_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateField(default='2018-01-24'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateField(default='2018-01-24'),
        ),
    ]
