# Generated by Django 2.0.1 on 2018-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0016_auto_20180124_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-01-24 16:35'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-01-24 16:35'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='time_left',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
