# Generated by Django 2.0.1 on 2018-01-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0019_auto_20180126_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='room',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='date',
            field=models.DateTimeField(default='2018-01-26 12:19'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='returning_date',
            field=models.DateTimeField(default='2018-01-26 12:19'),
        ),
    ]
