# Generated by Django 2.0.1 on 2018-01-18 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('times_up', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCard',
            fields=[
                ('usercard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserCards.UserCard')),
            ],
            bases=('UserCards.usercard',),
        ),
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('usercard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserCards.UserCard')),
            ],
            bases=('UserCards.usercard',),
        ),
    ]
