# Generated by Django 2.0.1 on 2018-02-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.CharField(default='https://cdn.onlinewebfonts.com/svg/img_507334.png', max_length=1000),
        ),
    ]
