# Generated by Django 2.0.1 on 2018-01-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='times_up',
        ),
        migrations.AddField(
            model_name='usercard',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
