# Generated by Django 2.0.1 on 2018-01-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCards', '0002_auto_20180119_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='password',
            field=models.CharField(default='123456', max_length=250),
        ),
    ]
