# Generated by Django 2.0.1 on 2018-01-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCards', '0003_usercard_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='surname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
