# Generated by Django 2.0.1 on 2018-01-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCards', '0004_auto_20180119_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='session_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
