# Generated by Django 2.0.1 on 2018-02-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserCards', '0004_auto_20180204_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
