# Generated by Django 2.0.4 on 2018-04-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCards', '0005_remove_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privileges',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
