# Generated by Django 2.0.1 on 2018-01-30 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserCards', '0006_customuser_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Universitetskya 1', max_length=250)),
                ('phone_number', models.IntegerField(default=11111)),
                ('status', models.CharField(default='student', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
