# Generated by Django 2.0.1 on 2018-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCards', '0006_userprofile_privileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='privileges',
            field=models.CharField(default='no privileges', max_length=250),
        ),
    ]
