# Generated by Django 2.0.1 on 2018-02-04 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_auto_20180204_0820'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookRequests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookRequest',
            new_name='Request',
        ),
    ]
