# Generated by Django 2.0.1 on 2018-03-12 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookRequests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='checked_up_by_whom',
        ),
        migrations.AddField(
            model_name='request',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
