# Generated by Django 2.0.3 on 2018-03-31 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0010_auto_20180331_1105'),
        ('BookRequests', '0002_auto_20180312_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutStandingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Documents.Document')),
            ],
        ),
    ]
