# Generated by Django 2.0.3 on 2018-04-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookRequests', '0003_outstandingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstandingrequest',
            name='timestamp',
        ),
    ]
